version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose          # checks whether HTTP response body is closed successfully
    - dogsled            # checks assignments with too many blank identifiers
    - dupl               # code clone detection  
    - errcheck           # checks for unchecked errors
    - exhaustive         # checks exhaustiveness of enum switch statements
    - gochecknoinits     # checks that no init functions are present
    - goconst            # finds repeated strings that could be replaced by a constant
    - gocritic           # provides diagnostics that check for bugs, performance and style issues
    - gocyclo            # computes and checks the cyclomatic complexity of functions
    - goprintffuncname   # checks that printf-like functions are named with f at the end
    - gosec              # inspects source code for security problems
    - govet              # reports suspicious constructs (go vet)
    - ineffassign        # detects when assignments to existing variables are not used
    - lll                # reports long lines
    - nakedret           # finds naked returns in functions greater than a specified function length
    - noctx              # finds sending HTTP request without context.Context
    - nolintlint         # reports ill-formed or insufficient nolint directives
    - prealloc           # finds slice declarations that could potentially be preallocated
    - revive             # fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck       # checks whether Err of rows is checked successfully
    - staticcheck        # staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - unconvert          # removes unnecessary type conversions
    - unparam            # reports unused function parameters
    - whitespace         # detection of leading and trailing whitespace
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - commentedOutCode
        - importShadow
        - paramTypeCombine
        - rangeValCopy
        - httpNoBody
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 215
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      confidence: 0
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - ineffassign
          - rowserrcheck
          - govet
          - revive
          - unparam
        path: _test\.go
      - linters:
          - gocyclo
          - ineffassign
        path: pkg/mock/
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - ineffassign
        path: cmd/.*/main\.go
      - linters:
          - gocyclo
        path: pkg/parser/
        text: cyclomatic complexity
      - linters:
          - unused
        text: 'field .* is unused'
        path: internal/modules/
      - linters:
          - dupl
        path: internal/modules/products/http/(handlers|handlers_test)\.go
      - linters:
          - gosec
          - revive
        path: internal/modules/shared/
      - linters:
          - gosec
        text: 'G115.*integer overflow'
    paths:
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
