-- V3: Upgrade the outbox ledger to the go-bricks v0.61.0+ shape
-- Source: ADR-088 and go-bricks wiki/outbox.md ("Managed migration"). Rows now drain
-- ORDER BY seq under a single relay leader, so the ledger gains seq/lane/stream/
-- partition_key plus the companion gobricks_outbox_leader table.
--
-- outbox.autocreatetable is false, so this file is the sole owner of gobricks_outbox DDL.
--
-- DUAL-PATH CONTRACT: the same final schema must come out of both
--   (a) a retained volume holding the v0.60.0-shaped gobricks_outbox — CREATE is a no-op,
--       the guarded ALTER + seq backfill + setval run; and
--   (b) a fresh volume with no outbox table — CREATE lands the full shape, the guarded
--       ALTER is skipped and the backfill/setval see an empty ledger.
-- The four new columns are declared LAST in the CREATE so a fresh table carries the same
-- ordinal order that ALTER ... ADD COLUMN produces on a retained one.
-- This DELIBERATELY diverges from the framework's own CreateTable (outbox/store_postgres.go),
-- which interleaves them at ordinals 2-3 (seq, lane) and 10-11 (stream, partition_key); here
-- they sit at 13-16. The divergence is inert because every framework DML names its columns
-- explicitly (outbox/store_sql.go pendingColumns) and never relies on positional order — and
-- picking ALTER's order is what makes the retained and fresh paths physically identical.
--
-- Flyway runs this in ONE transaction: the ALTER's ACCESS EXCLUSIVE lock blocks writers
-- from there through the sequence reset. Safe against a racing insert, a write outage to
-- schedule on a large ledger.

-- Path (b): full v0.61.0+ shape. No-op when the table already exists.
CREATE TABLE IF NOT EXISTS gobricks_outbox (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type    VARCHAR(255) NOT NULL,
    aggregate_id  VARCHAR(255) NOT NULL,
    payload       BYTEA NOT NULL,
    headers       BYTEA,
    exchange      VARCHAR(255) NOT NULL DEFAULT '',
    routing_key   VARCHAR(255) NOT NULL DEFAULT '',
    status        VARCHAR(20) NOT NULL DEFAULT 'pending',
    retry_count   INTEGER NOT NULL DEFAULT 0,
    error         TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    published_at  TIMESTAMP WITH TIME ZONE,
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lane          VARCHAR(16) NOT NULL DEFAULT 'amqp',
    stream        VARCHAR(255) NOT NULL DEFAULT '',
    partition_key VARCHAR(255) NOT NULL DEFAULT ''
);

-- Path (a): the v0.60.0 table has none of the four columns.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'gobricks_outbox'
          AND column_name = 'seq'
    ) THEN
        ALTER TABLE gobricks_outbox
            ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
            ADD COLUMN lane VARCHAR(16) NOT NULL DEFAULT 'amqp',
            ADD COLUMN stream VARCHAR(255) NOT NULL DEFAULT '',
            ADD COLUMN partition_key VARCHAR(255) NOT NULL DEFAULT '';
    END IF;
END $$;

-- The backfill is not optional on path (a): adding an identity column numbers existing rows
-- in heap order, and the outbox updates pending rows, so the divergence from created_at order
-- lands precisely on the retried rows a backlog is made of.
WITH ordered AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
    FROM gobricks_outbox
)
UPDATE gobricks_outbox o
SET seq = ordered.rn
FROM ordered
WHERE o.id = ordered.id;

-- Three-argument setval: an empty ledger has no max, and setval(seq, 0) violates MINVALUE 1.
SELECT setval(pg_get_serial_sequence('gobricks_outbox', 'seq'),
              (SELECT coalesce(max(seq), 1) FROM gobricks_outbox),
              (SELECT max(seq) IS NOT NULL FROM gobricks_outbox));

-- v0.60.0 indexed the pending partition on (created_at); the relay now orders by seq.
DROP INDEX IF EXISTS idx_gobricks_outbox_pending;
CREATE INDEX idx_gobricks_outbox_pending ON gobricks_outbox (seq) WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_gobricks_outbox_published ON gobricks_outbox (published_at) WHERE status = 'published';

-- The relay takes this single row FOR UPDATE NOWAIT so one instance per ledger drains at a time.
CREATE TABLE IF NOT EXISTS gobricks_outbox_leader (id SMALLINT PRIMARY KEY);
INSERT INTO gobricks_outbox_leader (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
